version: "3.9"
services:
  postgres:
    container_name: handsome-of-the-day-postgres
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
    volumes:
      - /handsome-of-the-day/Postgres:/docker-entrypoint-initdb.d
      - botdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - bot_network

  pgadmin:
    container_name: handsome-of-the-day-pgadmin
    image: dpage/pgadmin4:8.6
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - bot_network

  bot:
    container_name: handsome-of-the-day-bot
    image: handsome-of-the-day-bot
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - USER=${BOT_USER}
      - PASSWORD=${BOT_PASSWORD}
      - HOST=${BOT_HOST}
      - PORT=${BOT_PORT}
      - DATABASE=${BOT_DATABASE}
      - CHAT_ID=${BOT_CHAT_ID}
    volumes:
      - /handsome-of-the-day/logs:/handsome-of-the-day/Bot/logs
    restart: unless-stopped
    networks:
      - bot_network

volumes:
  botdb-data:
  pgadmin-data:
networks:
  bot_network:
    driver: bridge
